# Generated by Django 3.1.7 on 2021-03-31 14:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_masters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='note',
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(default='1', max_length=1),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_masters.task')),
            ],
            options={
                'verbose_name_plural': 'notes',
            },
        ),
    ]
