# Generated by Django 3.1.7 on 2021-04-11 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_masters', '0003_task_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='date_completed',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
